# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aGsIiHlpdJRu_rHYKF6OGNRlM_vG1GE2
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# -----------------------------
# Load Best Model (Random Forest)
# -----------------------------
# Initialize and train the Random Forest Classifier model
import streamlit as st
import pandas as pd
import numpy as np
import joblib
from sklearn.ensemble import RandomForestClassifier      # REQUIRED

model = joblib.load("best_model.pkl")

try:
    scaler = joblib.load("scaler.pkl")
except:
    scaler = None

rfc_model.fit(X_train, y_train)

# Make predictions on the test set
rfc_y_pred = rfc_model.predict(X_test)

# Evaluate the model
print("\nRandom Forest Model Evaluation:")
print(f"Accuracy: {accuracy_score(y_test, rfc_y_pred):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, rfc_y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, rfc_y_pred))

# Export the trained Random Forest Classifier model
joblib.dump(rfc_model, "best_model.pkl")

# Export the fitted scaler
joblib.dump(scaler, "scaler.pkl")

print("\nRandom Forest Classifier model saved as best_model.pkl")
print("Scaler saved as scaler.pkl")
# -----------------------------
# Streamlit UI
# -----------------------------
st.set_page_config(page_title="Alzheimer's Predictor", layout="wide")
st.title("🧠 Alzheimer's Disease Prediction (Best Model: Random Forest)")
st.write("Enter patient information below to predict the likelihood of Alzheimer's disease.")

col1, col2 = st.columns(2)

with col1:
    Age = st.number_input("Age", min_value=1, max_value=120, value=65)
    Gender = st.selectbox("Gender", ["Male", "Female"])
    Education = st.number_input("Education Level (years)", min_value=0, max_value=25, value=12)
    MMSE = st.number_input("MMSE Score (0–30)", min_value=0.0, max_value=30.0, value=22.0)

with col2:
    Memory = st.number_input("Memory Score (0–100)", min_value=0.0, max_value=100.0, value=50.0)
    Cognitive = st.number_input("Cognitive Score (0–100)", min_value=0.0, max_value=100.0, value=55.0)
    Brain = st.number_input("Brain Scan Result (0–10)", min_value=0.0, max_value=10.0, value=5.0)

# Convert Gender to numeric
Gender_num = 1 if Gender == "Male" else 0

# -----------------------------
# Prediction
# -----------------------------
if st.button("Predict Alzheimer's"):
    input_data = np.array([[
        Age,
        Gender_num,
        Education,
        MMSE,
        Memory,
        Cognitive,
        Brain
    ]])

    # Scale if scaler exists
    if scaler:
        input_data = scaler.transform(input_data)

    pred = model.predict(input_data)[0]
    prob = model.predict_proba(input_data)[0][1]

    st.subheader("🔍 Prediction Result")
    if pred == 1:
        st.error(f"⚠ Alzheimer's Detected\n\n**Probability: {prob:.2f}**")
    else:
        st.success(f"✅ No Alzheimer's Detected\n\n**Probability: {prob:.2f}**")
