# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12tNP5gscASuSSDfjXW3w6q4Jp03qzo0a
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# --- Configuration ---
st.set_page_config(
    page_title="Alzheimer's Disease Prediction",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- Load Model and Scaler ---
@st.cache_resource
def load_assets():
    """Loads the pre-trained model and scaler."""
    try:
        model = joblib.load('random_forest_model.pkl')
        scaler = joblib.load('scaler.pkl')
        return model, scaler
    except FileNotFoundError:
        st.error("Error: Model or Scaler file not found. Please run 'save_model.py' first.")
        st.stop()

model, scaler = load_assets()

# The 32 feature names, in the exact order used for training
FEATURE_NAMES = [
    'Age', 'Gender', 'Ethnicity', 'EducationLevel', 'BMI', 'Smoking', 'AlcoholConsumption',
    'PhysicalActivity', 'DietQuality', 'SleepQuality', 'FamilyHistoryAlzheimers',
    'CardiovascularDisease', 'Diabetes', 'Depression', 'HeadInjury', 'Hypertension',
    'SystolicBP', 'DiastolicBP', 'CholesterolTotal', 'CholesterolLDL', 'CholesterolHDL',
    'CholesterolTriglycerides', 'MMSE', 'FunctionalAssessment', 'MemoryComplaints',
    'BehavioralProblems', 'ADL', 'Confusion', 'Disorientation', 'PersonalityChanges',
    'DifficultyCompletingTasks', 'Forgetfulness'
]

# --- UI Layout ---
st.title("🧠 Alzheimer's Disease Risk Classification")
st.markdown("Use the input form below to assess a patient's risk of Alzheimer's Disease.")
st.divider()

# Input collection function
def get_user_input():
    with st.form("prediction_form"):
        st.header("Patient Demographic & Lifestyle")
        col1, col2, col3 = st.columns(3)

        with col1:
            age = st.slider("Age", 40, 95, 70)
            gender = st.selectbox("Gender", options=[(0, "Female"), (1, "Male")], format_func=lambda x: x[1])[0]
            # Assuming 0-4 are numerical codes for categories
            ethnicity = st.number_input("Ethnicity (Numerical Code)", 0, 4, 1, help="Use numerical codes, e.g., 0-4.")

        with col2:
            education = st.number_input("Education Level (Years)", 0, 20, 12)
            bmi = st.slider("BMI", 15.0, 40.0, 25.0)
            smoking = st.radio("Smoking Status (0=No, 1=Yes)", (0, 1), index=0)

        with col3:
            alcohol = st.slider("Alcohol Consumption (Units/Week)", 0, 50, 5)
            activity = st.slider("Physical Activity (Hours/Week)", 0, 20, 3)
            diet = st.slider("Diet Quality Score (1-10)", 1, 10, 7)
            sleep = st.slider("Sleep Quality Score (1-10)", 1, 10, 6)

        st.header("Medical History & Vitals")
        col4, col5, col6 = st.columns(3)

        # Binary/Boolean features (0/1)
        with col4:
            st.subheader("Existing Conditions (0=No, 1=Yes)")
            family_history = st.radio("Family History of Alzheimer's", (0, 1), index=0, key='fh')
            cardio_disease = st.radio("Cardiovascular Disease", (0, 1), index=0, key='cd')
            diabetes = st.radio("Diabetes", (0, 1), index=0, key='db')
            depression = st.radio("Depression", (0, 1), index=0, key='dp')
            head_injury = st.radio("Previous Head Injury", (0, 1), index=0, key='hi')
            hypertension = st.radio("Hypertension", (0, 1), index=0, key='ht')

        with col5:
            st.subheader("Clinical Measurements")
            systolic_bp = st.number_input("Systolic BP (mmHg)", 80, 200, 120)
            diastolic_bp = st.number_input("Diastolic BP (mmHg)", 40, 120, 80)

            st.subheader("Cholesterol Levels")
            chol_total = st.number_input("Cholesterol Total", 100, 300, 200)
            chol_ldl = st.number_input("Cholesterol LDL", 50, 200, 100)
            chol_hdl = st.number_input("Cholesterol HDL", 20, 100, 50)
            chol_trig = st.number_input("Cholesterol Triglycerides", 50, 500, 150)

        with col6:
            st.subheader("Cognitive & Behavioral Assessments")
            # MMSE (Mini-Mental State Exam) score: 0-30
            mmse = st.slider("MMSE Score (0-30)", 0, 30, 25, help="Assessment of cognitive impairment.")
            # Functional Assessment Score (e.g., higher is better function)
            functional_assessment = st.slider("Functional Assessment Score (0-100)", 0, 100, 80, help="Higher is better daily function.")
            # ADL (Activities of Daily Living) score (assuming higher is better function)
            adl = st.slider("ADL Score (0-50)", 0, 50, 40, help="Higher score indicates better independence in ADL.")

            st.subheader("Symptoms (0=No, 1=Yes)")
            memory_complaints = st.radio("Memory Complaints", (0, 1), index=0, key='mc')
            behavioral_problems = st.radio("Behavioral Problems", (0, 1), index=0, key='bp')
            confusion = st.radio("Confusion", (0, 1), index=0, key='cf')
            disorientation = st.radio("Disorientation", (0, 1), index=0, key='do')
            personality_changes = st.radio("Personality Changes", (0, 1), index=0, key='pc')
            difficulty_tasks = st.radio("Difficulty Completing Tasks", (0, 1), index=0, key='dt')
            forgetfulness = st.radio("Forgetfulness", (0, 1), index=0, key='fg')

        # Combine inputs into a dictionary in the correct order
        input_data = {
            'Age': age, 'Gender': gender, 'Ethnicity': ethnicity, 'EducationLevel': education,
            'BMI': bmi, 'Smoking': smoking, 'AlcoholConsumption': alcohol,
            'PhysicalActivity': activity, 'DietQuality': diet, 'SleepQuality': sleep,
            'FamilyHistoryAlzheimers': family_history, 'CardiovascularDisease': cardio_disease,
            'Diabetes': diabetes, 'Depression': depression, 'HeadInjury': head_injury,
            'Hypertension': hypertension, 'SystolicBP': systolic_bp, 'DiastolicBP': diastolic_bp,
            'CholesterolTotal': chol_total, 'CholesterolLDL': chol_ldl, 'CholesterolHDL': chol_hdl,
            'CholesterolTriglycerides': chol_trig, 'MMSE': mmse, 'FunctionalAssessment': functional_assessment,
            'MemoryComplaints': memory_complaints, 'BehavioralProblems': behavioral_problems,
            'ADL': adl, 'Confusion': confusion, 'Disorientation': disorientation,
            'PersonalityChanges': personality_changes, 'DifficultyCompletingTasks': difficulty_tasks,
            'Forgetfulness': forgetfulness
        }

        submitted = st.form_submit_button("Predict Alzheimer's Risk")

    return submitted, input_data

# --- Prediction Logic ---
def make_prediction(input_data):
    # Convert input dictionary to DataFrame
    input_df = pd.DataFrame([input_data])

    # 1. Ensure columns are in the exact order used for training
    input_df = input_df[FEATURE_NAMES]

    # 2. Replicate imputation (using mean of training set data if necessary,
    # but since we imputed everything in save_model.py, this step is for safety)
    # The saved scaler handles all necessary scaling

    # 3. Scale the input data
    input_scaled = scaler.transform(input_df)

    # 4. Make prediction
    prediction = model.predict(input_scaled)[0]
    prediction_proba = model.predict_proba(input_scaled)[0]

    return prediction, prediction_proba

# --- Main App Execution ---
submitted, input_data = get_user_input()

if submitted:
    prediction, prediction_proba = make_prediction(input_data)

    st.subheader("Prediction Result")

    # Display the result
    if prediction == 1:
        st.error("Based on the input features, the model predicts a **HIGH RISK** of Alzheimer's Disease (Diagnosis=1).")
    else:
        st.success("Based on the input features, the model predicts a **LOW RISK** of Alzheimer's Disease (Diagnosis=0).")

    st.subheader("Prediction Confidence")
    # Probability for class 1 (Alzheimer's)
    risk_percent = prediction_proba[1] * 100
    st.info(f"The predicted probability of Alzheimer's (Diagnosis=1) is **{risk_percent:.2f}%**.")

    # Add a gauge or chart for visualization
    st.metric(label="Alzheimer's Risk Probability", value=f"{risk_percent:.2f}%")
    st.progress(risk_percent / 100)